### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'key')

### ISSUE THREAD

**Issue by longlongvip** [mumingfang/jvmaoTab#2]
## 图示
![image](https://github.com/user-attachments/assets/1bf7b0ab-5fda-48dd-9b80-8e4d8a29e25f)

## 错误信息
TypeError: Cannot read properties of undefined (reading 'key')

## 控制台报错信息
```err
styled-components.browser.esm-1bf82734.js:40 TypeError: Cannot read properties of undefined (reading 'key')
    at Home-72e65540.js:290:819
    at Mi (LinkItem-641d9e62.js:28:17514)
    at c9 (Home-72e65540.js:290:705)
    at index-ee2f2b80.js:102:52792
    at index-ee2f2b80.js:102:51969
    at q1 (index-ee2f2b80.js:102:12963)
    at t.track (index-ee2f2b80.js:102:17819)
    at O8 (index-ee2f2b80.js:102:51946)
    at s (index-ee2f2b80.js:102:52771)
    at Cm (styled-components.browser.esm-1bf82734.js:38:17028)
```

## 导出的数据
```json
{
  "formatName": "dexie",
  "formatVersion": 1,
  "data": {
    "databaseName": "jvmao-tab",
    "databaseVersion": 1.4,
    "tables": [
      {
        "name": "link",
        "schema": "++linkId,title,url,&timeKey,sort,parentId,hide",
        "rowCount": 0
      },
      {
        "name": "option",
        "schema": "++id,&key,value",
        "rowCount": 1
      },
      {
        "name": "note",
        "schema": "++id,content,createTime,updateTime,fromUrl,sort",
        "rowCount": 0
      }
    ],
    "data": [{
      "tableName": "link",
      "inbound": true,
      "rows": []
    },{
      "tableName": "option",
      "inbound": true,
      "rows": [
        {
          "key": "v",
          "value": 12,
          "id": 1
        }
      ]
    },{
      "tableName": "note",
      "inbound": true,
      "rows": []
    }]
  }
}
```

## 相关代码
```js
// styled-components.browser.esm-1bf82734.js
function Av(e, t) {
    try {
        console.error(t.value)
    } catch (n) {
        setTimeout(function() {
            throw n
        })
    }
}
```

**Comment by mumingfang** [comment]
很奇怪是什么原因 option表是空的，或者你故意修改过json，应该是搜索源的基础数据没有了导致的  
![QQ20241120-204612](https://github.com/user-attachments/assets/06671817-5688-46ae-850a-cf25144e3649)

跟着截图做一遍，option表里的 v 字段是控制默认版本的，直接删除会重置一下所有选项。

现在（1.2.7）这个重置按钮 还是一个临时的功能，没有做loading结束，等一会看到option表发生数据变化了就可以 刷新了

**Comment by longlongvip** [comment]
> 很奇怪是什么原因 option表是空的，或者你故意修改过json，应该是搜索源的基础数据没有了导致的 ![QQ20241120-204612](https://private-user-images.githubusercontent.com/17588549/388097633-06671817-5688-46ae-850a-cf25144e3649.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMTA1NDUsIm5iZiI6MTczMjExMDI0NSwicGF0aCI6Ii8xNzU4ODU0OS8zODgwOTc2MzMtMDY2NzE4MTctNTY4OC00NmFlLTg1MGEtY2YyNTE0NGUzNjQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDEzNDQwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxNGI4MjA2NGU1ZjM5YTRhNjVmMWY1OWFkNzIwNTdmYThiODdhYzc3NzMwMTA3MzA0YTY5YWEzOGNhOWI0NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mB8_Rr6W7EwpUalb9fZKQK1QgDTYtmKBT_DegCCLxmA)
> 
> 跟着截图做一遍，option表里的 v 字段是控制默认版本的，直接删除会重置一下所有选项。
> 
> 现在（1.2.7）这个重置按钮 还是一个临时的功能，没有做loading结束，等一会看到option表发生数据变化了就可以 刷新了

好使
